### ISSUE TITLE
Bit fields not supported

### ISSUE THREAD

**Issue by amzeratul** [Viladoman/StructLayout#15]
Members which belong to a bit field currently show as a "hole" in the visualization. Here's an example from my project:

![image](https://user-images.githubusercontent.com/4175191/97809958-5a2ce400-1c68-11eb-88d0-e6528146b2a4.png)

![image](https://user-images.githubusercontent.com/4175191/97809947-44b7ba00-1c68-11eb-942e-bec1dfc54464.png)

**Comment by Viladoman** [comment]
Sorry about that. This is in my todo list. [Bitfield detection code](https://github.com/Viladoman/StructLayout/blob/main/LayoutParser/src/Parser/Parser.cpp#L195)

I had doubts about how to visualize them, so I left them out for the first implementation. I might do it similar to what has been done with empty base optimizations. Something like displaying the big chunk (byte based) in the view and the individual bits inside in the tooltip.

**Comment by Viladoman** [comment]
Just submitted version 0.3 which should fix this. Let me know if there are still issues with bitfields.
