### ISSUE TITLE
Support for Visual Studio Property Sheet

### ISSUE THREAD

**Issue by Alekssasho** [Viladoman/StructLayout#17]
Automatic extraction of include dirs are not working if those include dirs are coming from a Property Sheet. In my project I use Property Sheets to configure include dirs/linkers dirs and so on, to avoid having to define them for every project. However the automatic extraction process is not working correctly

**Comment by Viladoman** [comment]
Good point! I have never worked with property sheets before. I will have a look!

**Comment by Viladoman** [comment]
Version 0.4.1 should be able to capture the include paths from the property sheets.

Sadly I spent some time trying to figure out the best way to extract the property sheet information. I did not find a reliable way to get all the full property sheet data from inside the VS SDK, but I managed to find a way to get all the include paths from there.

**Comment by Alekssasho** [comment]
Tested it and it works great. Thanks for the support. Really useful tool.
