### ISSUE TITLE
Data member names are overlaid.

### ISSUE THREAD

**Issue by x-santiaga-x** [Viladoman/StructLayout#20]
There are member display error for member at 0x18
for structure
`struct aaa : boost::container::small_vector<int, 10> { };`
where members _aligner_ and _data_ placed.
I click "Expand all" and then click on the _data_ outer area to display _aligner_ and the text is overlaid.

![image](https://user-images.githubusercontent.com/37975005/101329302-446f9780-3882-11eb-8bc9-574fb0382e70.png)

**Comment by Viladoman** [comment]
I finally had a chance to have a look at this. 

When more than one member are sharing the same memory address outside a union I added a 'Shared memory' node. 

On top of it to improve navigation, unions and shared memory nodes now allow to chose which member we want to expand. 

In version 0.4.2 the *aaa* struct should look like this: 

![image](https://user-images.githubusercontent.com/8118743/102255613-4d8ee300-3ed8-11eb-88a8-b55f11201630.png)
