### ISSUE TITLE
Unions don't appear to be supported

### ISSUE THREAD

**Issue by jeremyong** [Viladoman/StructLayout#23]

**Comment by Viladoman** [comment]
Unions should display if inside a structure or class. 
You are right, they won't show up at the declaration level. Good catch, thanks for reporting it. 
I will have a look when I have some time.

**Comment by jeremyong** [comment]
Thanks! And yea, I noticed that if I wrapped a union inside a struct/class the layout worked properly. Cheers

**Comment by Viladoman** [comment]
Sorry for the late update on this. On version 0.4.6 you should be able to inspect union declarations directly. 

I still need to improve how they are visualized, as by default on structs and classes I expand the first level. But I will handle that on a further update. 

Direct union inspection will now look something like this: 

![image](https://user-images.githubusercontent.com/8118743/113052980-c9eebe80-9175-11eb-9388-02728937f50f.png)

Thanks for your feedback!

**Comment by jeremyong** [comment]
Great work thanks!
