### ISSUE TITLE
Error dialog - "Unable to retrieve the project configuration"

### ISSUE THREAD

**Issue by Pnyxor** [Viladoman/StructLayout#25]
I just installed this VisualStudio extension, and consistently get the dialog box error, making the extension unusable.
This is a standard C++ VS project, and it definitely has a valid project configuration.

**Comment by Viladoman** [comment]
I am sad to hear that. 
Does it work for you with the sample project included in this repository?

**Comment by Pnyxor** [comment]
What ‘sample project’ in what ‘repository’?

**Comment by Viladoman** [comment]
[This one](https://github.com/Viladoman/StructLayout/tree/main/TestProjects/Regular) (this is my basic test run project). This would indicate if there is something slightly different on your setup that I am not considering at the moment or there is some conflict somewhere making the extension fail to access the project configuration.

**Comment by Pnyxor** [comment]
Sorry, Ramon, but I’m not going to do this. Yes, I am interested in finding what is odd about this, but I don’t think it is MY responsibility to do that.

I am a programmer who has always been concerned about performance and memory usage (my programming experience starts when CP/M was young, and thus efficient memory usage and getting the best performance from our hardware was important). So, when I saw that you had a VisualStudio extension that could show me the layout of C structs (and thus C++ classes), I was encouraged to try it.

But let me re-emphasize: I have a smallish project that I have been working on for some time. It is a straight-forward, valid and authentic C++ VisualStudio project. In order to test your extension, I clicked on an extremely simple C struct that only consisted of FOUR unsigned short values. This led to your Dialog Box error message! And there was no hint as to what that might mean and how to resolve it.

By reading between the lines in your description of StructLayout, it seems that you wrote this extension for a very particular need and thus a particular audience. If the extension cannot be used in a plain VisualStudion C++ project, you should make note of that.

I do not feel that it is MY job to help you debug or correct this.

Richard

**Comment by Viladoman** [comment]
Thanks for giving it a try, I would have loved to at least have some data to improve it, at the end of the day I am coding and maintaining this extension for free by myself during my spare time ( not my job either :) ). I understand everybody's time is important.

I am closing this given the fact that I don't have more information. Thanks for reaching out.

**Comment by Pnyxor** [comment]
If you think you have some ideas of what might make your extension work (for instance, to tell more about why it cannot retrieve the project configuration), I would be happy to try some new versions. As I said, I would like to use this.
