### ISSUE TITLE
Not working with std::string_view

### ISSUE THREAD

**Issue by RisingLiberty** [Viladoman/StructLayout#3]
code: 
#include <string_view>

void f()
{
	std::string_view name, prefix, suffix;
}

struct MyStruct
{
	int x, y, z;
};

output:
[19:23:57] Looking for structures at D:\C++\Testing\TestCode\TestCode\src\struct_layout.cpp:8:11...
[19:23:57] COMMAND LINE: D:\C++\Testing\TestCode\TestCode\src\struct_layout.cpp -- -x c++ -m64 -w -DFORCE_STATIC_VCRT -D_MBCS -ID:\C++\Testing\TestCode\TestCode\SDL\ -ID:\C++\Testing\TestCode\TestCode\include
[19:23:57] Execution Log:
D:\C++\Testing\TestCode\TestCode\src\struct_layout.cpp:5:7: error: no type named 'string_view' in namespace 'std'
        std::string_view name, prefix, suffix;
        ~~~~~^
1 error generated.
Error while processing D:\C++\Testing\TestCode\TestCode\src\struct_layout.cpp.

[19:23:57] [ERROR] Unable to scan the given location. (37.0765 ms)

**Comment by Viladoman** [comment]
Gladly I could quickly reproduce in a simple test project. 
The issue is that std::string_view is a C++17 feature and by default the parser is using C++14 (afaik). 

As a workaround you could try to go to the Struct Layout options and add this: 
![image](https://user-images.githubusercontent.com/8118743/97368147-b23aa380-1880-11eb-85f6-0faa49b88c85.png)

The options are at the bottom-left of the Struct Layout Tool Window. 

I will keep this issue open as I think it might be interesting to capture the c++ standard version automatically from the Project properties.

Let me know if this fixes it!

**Comment by RisingLiberty** [comment]
yea I figured that was it, good luck getting it from the project settings, VS extension dev is a pain :p

**Comment by lukaasm** [comment]
> Gladly I could quickly reproduce in a simple test project.
> The issue is that std::string_view is a C++17 feature and by default the parser is using C++14 (afaik).
> 
> As a workaround you could try to go to the Struct Layout options and add this:
> ![image](https://user-images.githubusercontent.com/8118743/97368147-b23aa380-1880-11eb-85f6-0faa49b88c85.png)
> 
> The options are at the bottom-left of the Struct Layout Tool Window.
> 
> I will keep this issue open as I think it might be interesting to capture the c++ standard version automatically from the Project properties.
> 
> Let me know if this fixes it!

The problem with that is, you need to have open Struct Layout Window first which doesn't happen when there are parsing errors.

As a workaround you need to go/create a standalone file without any includes, create struct and PPM to open Struct Layout Window. And now you can open settings and add additional args.

It would be awesome if extension contributed additional toolbar button/VS Settings entry for easier access to tool options.

**Comment by Viladoman** [comment]
I just submitted version 0.2.2 which should autodetect the language version from the project configuration. 

@lukaasm I think adding a command for the options directly in the Tools tab is a good idea, I will do it. As a workaround, without having to create an empty file, you can open the tool window directly here: 

![image](https://user-images.githubusercontent.com/8118743/97522337-ed6ace80-1975-11eb-9589-3210e6446bfc.png)

Let me know if the issue got fixed at your end.

**Comment by RisingLiberty** [comment]
Yep, seems to work now, thanks! :)

**Comment by Viladoman** [comment]
Awesome! Thanks for verifying it!
