### ISSUE TITLE
stucking at processing...

### ISSUE THREAD

**Issue by illegal-instruction-co** [Viladoman/StructLayout#35]
I am stucking at processing as you can see:
https://prnt.sc/_ajwEkRn9lGw

I implemented -DCMAKE_EXPORT_COMPILE_COMMANDS=1 to my cmake build.cmd

**Comment by aolbrech** [comment]
Encountering the same issue. Tried it both in Visual Studio 2022 and Visual Studio 2019.
Used the TestProjects/Regular codebase.

**Comment by illegal-instruction-co** [comment]
> Encountering the same issue. Tried it both in Visual Studio 2022 and Visual Studio 2019. Used the TestProjects/Regular codebase.

I guess this project is kinda sleeping for a long time.

**Comment by Viladoman** [comment]
I have seen this behavior happen in the past, but I have been unable to reproduce it locally sadly. 
If someone has the time to breakpoint it and see where it is getting stuck I would really appreciate it. 

I don't have a lot of bandwidth at the moment.

**Comment by nedwardsnae** [comment]
I encountered this issue - PR #38 should address it

**Comment by Viladoman** [comment]
This issue should be fixed on version 0.6.2+. Thanks for the help.
