### ISSUE TITLE
FYI: Visual Studio just added this functionality

### ISSUE THREAD

**Issue by s9w** [Viladoman/StructLayout#42]
Not sure if you were involved. But they apparently liked the idea :)  

See https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.9.0-pre.1.0

**Comment by Viladoman** [comment]
Oh wow! I was not involved at all, but it looks like they got inspired somewhere. I will have to give it a try. 

Thanks for sharing.
