### ISSUE TITLE
Visual Studio 2017 support?

### ISSUE THREAD

**Issue by Unit2Ed** [Viladoman/StructLayout#6]
Is it possible to get Visual Studio 2017 support for this extension? It looks super useful, but we haven't taken the plunge on 2019 yet.

**Comment by Viladoman** [comment]
Sorry for the late reply. I would love to have a look to this once the extension is more stable across different configurations.

**Comment by Viladoman** [comment]
I finally got some time to have a look at this. It was way simpler than I expected. Version 0.4.5 should also work on VS 2017. I haven't tested it much, so please let me know if there are any strange issues with it.

**Comment by Unit2Ed** [comment]
It's working very nicely, thank you!
